using UnityEngine;

/// <summary>
/// The plant component: connects the simulation (PlantSimulation), the visuals (PlantVisuals)
/// and the parameters (a PlantSettings asset, optionally a randomized copy of it).
/// - Fixed simulation time step (settings.deltaT), decoupled from render framerate.
/// - Seeded: same settings + same seed => same plant.
/// </summary>
[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class PlantGrowth : MonoBehaviour// inheritance makes this class a component, name must match script name
{
    [Tooltip("Asset with all growth parameters. Create via Create -> Plant -> Plant Settings.")]
    public PlantSettings settings;
    public int seed = 42;
    [Tooltip("Growth is biased toward this point. If empty, biased straight up.")]
    public Transform lightSource;//scene object -> can't live in the settings asset
    [Tooltip("Layers whose colliders block growth (e.g. the terrarium glass on an 'Obstacle' layer). Nothing = no collisions.")]
    public LayerMask obstacleLayers;
    [Tooltip("Draw the collision boxes of all leaves/flowers in the Scene view (while playing).")]
    public bool showCollisionShapes;
    [Tooltip("Sim seconds per real second (0 = paused).")]
    [Range(0f, 20f)] public float simSpeed = 1f;//speed of overall simulation relative to real time
    [Tooltip("Tick to restart growth from scratch with the current seed (and current, possibly randomized, settings).")]
    public bool regrow;//immediately set back to false when clicked -> acts like toggle for reset
    const int MaxStepsPerFrame = 200;

    [Header("Phases")]
    [Tooltip("Current life phase (read-only, shown for information).")]
    public PlantPhase currentPhase;
    [Tooltip("Tick: end the current phase now and move on to the next enabled one (for testing).")]
    public bool skipToNextPhase;

    [Header("Randomization")]
    [Tooltip("How strongly Randomize varies the settings: 0 = no change, 1 = std of a quarter of each slider's range.")]
    [Range(0f, 1f)] public float randomizeStrength = 0.3f;
    [Tooltip("Also draw a new plant seed when randomizing.")]
    public bool alsoRandomizeSeed = false;
    [Tooltip("Tick: vary the settings asset's values randomly (the asset itself stays unchanged) and regrow.")]
    public bool randomize;
    [Tooltip("Tick: drop the randomization and regrow with the settings asset's own values.")]
    public bool useOriginalSettings;
    [Tooltip("Counts up with every Randomize. Asset values + strength + this number => same randomized settings.")]
    public int randomizationSeed = 0;
    [Tooltip("Generated by Randomize (read-only, lives only in memory). Click it to see its values; " +
             "keep it via the component menu: Save Randomized Settings As Asset.")]
    public PlantSettings randomizedSettings;

    PlantSimulation sim;
    PlantVisuals visuals;
    float accumulator;       // unconsumed real time * simSpeed
    bool meshDirty;          // flag, that indicates if the mesh is out of date and needs rebuilding
    int settingsVersion = -1;// last seen PlantSettings.Version, to notice slider changes in the asset
    PlantSettings randomizedFrom;//the asset randomizedSettings was made from

    /// <summary>The current simulation (read-only access for other scripts, e.g. logging).</summary>
    public PlantSimulation Simulation => sim;

    /// <summary>The settings actually used: the randomized copy if there is one, otherwise the asset.</summary>
    public PlantSettings ActiveSettings => randomizedSettings != null ? randomizedSettings : settings;

    void Awake()
    {
        randomizedSettings = null;//a copy from a previous Play session doesn't exist anymore
        visuals = new PlantVisuals(transform, GetComponent<MeshFilter>(), GetComponent<MeshRenderer>());
        ResetPlant();
    }

    [ContextMenu("Regrow")]
    public void ResetPlant()
    {
        if (visuals == null) return;//not in Play mode yet
        visuals.Clear();
        accumulator = 0f;
        meshDirty = true;
        PlantSettings s = ActiveSettings;
        sim = s != null ? new PlantSimulation(s, seed) : null;
        if (sim != null && obstacleLayers.value != 0)
        {
            sim.Obstacles = new UnityObstacleField(transform, obstacleLayers);
            //leaves and flowers need their size to be checked against obstacles before they appear
            if (s != shapesBuiltFor) BuildShapes(s);//prefabs are voxelized once per settings asset, not on every regrow
            sim.LeafShapes = leafShapes;
            sim.FlowerShapes = flowerShapes;
        }
        if (s == null) Debug.LogWarning("PlantGrowth: no PlantSettings asset assigned.", this);
    }

    OrganCompound[] leafShapes, flowerShapes;//collision shapes of the leaf/flower prefabs
    PlantSettings shapesBuiltFor;

    void BuildShapes(PlantSettings s)
    {
        leafShapes = BuildShapes(s.leafPrefabs, s.defaultVoxelResolution, keepRootScale: false);//leaves: visuals set their scale
        flowerShapes = BuildShapes(s.flowerPrefabs, s.defaultVoxelResolution, keepRootScale: true);//flowers: FlowerMorph keeps it
        shapesBuiltFor = s;
    }

    static OrganCompound[] BuildShapes(GameObject[] prefabs, int defaultResolution, bool keepRootScale)
    {
        if (prefabs == null) return null;
        var shapes = new OrganCompound[prefabs.Length];
        for (int i = 0; i < prefabs.Length; i++)
        {
            if (prefabs[i] == null) continue;
            var settingsOnPrefab = prefabs[i].GetComponent<OrganCollisionShape>();
            int res = settingsOnPrefab != null ? settingsOnPrefab.resolution : defaultResolution;
            shapes[i] = OrganVoxelizer.Build(prefabs[i], res);
            if (keepRootScale) shapes[i].rootScale = prefabs[i].transform.localScale.x;
            //flowers: copy the morph settings, so the simulation knows each flower's current state and size
            var morph = prefabs[i].GetComponent<FlowerMorph>();
            if (morph != null)
            {
                shapes[i].morph = new MorphInfo
                {
                    stageNames = morph.stages.ConvertAll(st => st.shapeName).ToArray(),
                    stageReachedAt = morph.stages.ConvertAll(st => st.reachedAt).ToArray(),
                    openState = morph.openStateName,
                    fruitState = morph.fruitStateName,
                    wiltFlowerState = morph.wiltFlowerStateName,
                    wiltFruitState = morph.wiltFruitStateName,
                    startScale = morph.startScale,
                    scaleExponent = morph.scaleExponent,
                };
            }
        }
        return shapes;
    }

    //Scene view: collision boxes of all leaves/flowers (only while playing, toggle showCollisionShapes)
    void OnDrawGizmos()
    {
        if (showCollisionShapes && sim != null && visuals != null)
            visuals.DrawCollisionShapes(leafShapes, flowerShapes, sim);
    }

    [ContextMenu("Randomize")]
    public void Randomize()
    {
        if (settings == null) { Debug.LogWarning("PlantGrowth: no PlantSettings asset to randomize.", this); return; }
        randomizationSeed++;
        //always starts from the asset's current values, not from the previous randomized copy
        PlantSettings copy = PlantSettingsRandomizer.Randomize(settings, randomizeStrength, randomizationSeed, out string changes);
        DropRandomizedCopy();
        randomizedSettings = copy;
        randomizedFrom = settings;
        if (alsoRandomizeSeed) seed = new System.Random(randomizationSeed).Next();
        Debug.Log($"PlantGrowth: randomized '{settings.name}' (strength {randomizeStrength:0.##}, " +
                  $"randomizationSeed {randomizationSeed}, plant seed {seed}):\n{changes}", this);
        ResetPlant();
    }

    [ContextMenu("Use Original Settings")]
    public void UseOriginalSettings()
    {
        DropRandomizedCopy();
        ResetPlant();
    }

    void DropRandomizedCopy()
    {
        if (randomizedSettings != null) Destroy(randomizedSettings);//copies made with Instantiate must be destroyed manually
        randomizedSettings = null;
        randomizedFrom = null;
    }

#if UNITY_EDITOR
    //editor-only code: saving assets isn't possible in a built game, so it's left out there
    [ContextMenu("Save Randomized Settings As Asset")]
    void SaveRandomizedAsAsset()
    {
        if (randomizedSettings == null || settings == null) { Debug.LogWarning("PlantGrowth: nothing randomized to save.", this); return; }
        string folder = System.IO.Path.GetDirectoryName(UnityEditor.AssetDatabase.GetAssetPath(settings));
        string path = UnityEditor.AssetDatabase.GenerateUniqueAssetPath(
            $"{folder}/{settings.name}_rand{randomizationSeed}.asset");
        PlantSettings asset = Instantiate(randomizedSettings);
        UnityEditor.AssetDatabase.CreateAsset(asset, path);
        UnityEditor.AssetDatabase.SaveAssets();
        Debug.Log($"PlantGrowth: saved randomized settings as {path} (plant seed {seed}).", asset);
    }
#endif

    //called by the editor when the component is added (or Reset from its menu): sensible default layer
    void Reset()
    {
        obstacleLayers = LayerMask.GetMask("Obstacle");
    }

    //called by the editor whenever a value on this component is changed in the inspector
    void OnValidate()
    {
        meshDirty = true;
    }

    void Update()
    {
        if (regrow) { regrow = false; ResetPlant(); }//immediately reset to false after regrow was pressed
        if (randomize) { randomize = false; Randomize(); }
        if (useOriginalSettings) { useOriginalSettings = false; UseOriginalSettings(); }
        if (skipToNextPhase) { skipToNextPhase = false; sim?.EnterNextPhase(); }
        //a different asset was assigned -> the randomized copy belongs to the old one, drop it
        if (randomizedSettings != null && randomizedFrom != settings) DropRandomizedCopy();

        //settings assigned or swapped for another asset -> start over with the new parameters
        PlantSettings s = ActiveSettings;
        if (s != null && (sim == null || sim.Settings != s)) ResetPlant();
        if (sim == null) return;

        //inverseTransform transforms the light source's global position to local relative to plant origin
        sim.LightTarget = lightSource != null ? transform.InverseTransformPoint(lightSource.position) : (Vector3?)null;

        //deltaTime is the actual time since last frame -> can vary depending on actual FPS
        //simulated time, that has passed in the real world, but wasn't simulated yet
        accumulator += Time.deltaTime * simSpeed;//avoids plant growing faster on fast PC
        float dt = s.deltaT;
        int steps = 0;
        //multiple steps are done in one frame if that frame takes too long to process on PC
        while (accumulator >= dt && steps < MaxStepsPerFrame)
        {
            if (sim.Step(dt)) meshDirty = true;
            accumulator -= dt;
            steps++;
        }
        //if the frames are so slow that many steps have to be done within (making the frame even slower), the game can freeze
        //capping maximum steps avoids this, even if step timing isn't accurate anymore
        if (steps == MaxStepsPerFrame) accumulator = 0f;

        //a slider in the settings asset was moved -> shape sliders take effect immediately, even while paused
        if (s.Version != settingsVersion) { settingsVersion = s.Version; meshDirty = true; }

        currentPhase = sim.Phase;
        if (meshDirty) { visuals.RebuildMesh(sim); meshDirty = false; }//updating how everything looks like after all the steps taken
        visuals.UpdateLeaves(sim);//cheap, so done every frame: leaf sizes and positions follow sliders immediately
        visuals.UpdateFlowers(sim);
    }

    void OnDestroy()
    {
        visuals?.Dispose();
        DropRandomizedCopy();
    }
}
